global:
  marketplace-ami: false
  owner: quickstart@amazon.com
  qsname: quickstart-datalake-qubole
  regions:
    - us-east-1
    - us-west-2
  reporting: true
tests:
  without-demonstration:
    parameter_input: qubole-without-demonstration.json
    template_file: qubole-data-lake-master.template
    regions:
      - us-west-2